RentCars/Models/CustomerModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace RentCars.Models
{
    [Table("Customers")]
    public class CustomerModel
    {
        [Key]
        public int CustomerId {get; set;}
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public string Steet { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Coutry { get; set; }
        public virtual ICollection<CarRentalModel> CarRentals { get; set; }
    }
}

RentCars/Controllers/CarRentalModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentCars.Models;

namespace RentCars.Controllers
{
    public class CarRentalModelsController : Controller
    {
        private CarRentalsModel db = new CarRentalsModel();

        // GET: CarRentalModels
        public ActionResult Index()
        {
            var carRentals = db.CarRentals.Include(c => c.Cars).Include(c => c.Customers);
            return View(carRentals.ToList());
        }

        // GET: CarRentalModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarRentalModel carRentalModel = db.CarRentals.Find(id);
            if (carRentalModel == null)
            {
                return HttpNotFound();
            }
            return View(carRentalModel);
        }


        public ActionResult Create(int id)
        {
            // ViewBag.CarId = new SelectList(db.Cars, "CarId", "Brand" + "Model");

            ViewBag.CarId = new SelectList((from s in db.Cars.ToList()
                            select new
                            {
                                CarId = s.CarId,
                                CarData = s.Brand + " " + s.Model+ " "+s.ProductionYear+" "+s.Colour
                            }),
                        "CarId",
                        "CarData",
                        null);


            CustomerModel customer = db.Customers.Single(a => a.CustomerId == id);

            CarRentalModel comm = new CarRentalModel();

            comm.CustomerId = id;
            return View(comm);

        }


        // POST: CarRentalModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CarRentalId,CustomerId,CarId,CarRentalDateFrom,CarRentalDateTo,CarRentalRate")] CarRentalModel carRentalModel)
        {
            if (ModelState.IsValid)
            {
                db.CarRentals.Add(carRentalModel);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return RedirectToAction("Index", "CustomerModels", "Index");
            }

            ViewBag.CarId = new SelectList(db.Cars, "CarId", "Brand", carRentalModel.CarId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CustomerName", carRentalModel.CustomerId);
            return View(carRentalModel);
        }

        // GET: CarRentalModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarRentalModel carRentalModel = db.CarRentals.Find(id);
            if (carRentalModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarId = new SelectList(db.Cars, "CarId", "Brand", carRentalModel.CarId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CustomerName", carRentalModel.CustomerId);
            return View(carRentalModel);
        }

        // POST: CarRentalModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CarRentalId,CustomerId,CarId,CarRentalDateFrom,CarRentalDateTo,CarRentalRate")] CarRentalModel carRentalModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(carRentalModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarId = new SelectList(db.Cars, "CarId", "Brand", carRentalModel.CarId);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CustomerName", carRentalModel.CustomerId);
            return View(carRentalModel);
        }

        // GET: CarRentalModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarRentalModel carRentalModel = db.CarRentals.Find(id);
            if (carRentalModel == null)
            {
                return HttpNotFound();
            }
            return View(carRentalModel);
        }

        // POST: CarRentalModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CarRentalModel carRentalModel = db.CarRentals.Find(id);
            db.CarRentals.Remove(carRentalModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RentCars/Controllers/CustomerModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RentCars.Models;

namespace RentCars.Controllers
{
    public class CustomerModelsController : Controller
    {
        private CarRentalsModel db = new CarRentalsModel();

        // GET: CustomerModels
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        // GET: CustomerModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerModel customerModel = db.Customers.Find(id);
            if (customerModel == null)
            {
                return HttpNotFound();
            }
            return View(customerModel);
        }

        // GET: CustomerModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerId,CustomerName,CustomerSurname,Steet,City,PostCode,Coutry")] CustomerModel customerModel)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customerModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customerModel);
        }

        // GET: CustomerModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerModel customerModel = db.Customers.Find(id);
            if (customerModel == null)
            {
                return HttpNotFound();
            }
            return View(customerModel);
        }

        // POST: CustomerModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerId,CustomerName,CustomerSurname,Steet,City,PostCode,Coutry")] CustomerModel customerModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customerModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customerModel);
        }

        // GET: CustomerModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerModel customerModel = db.Customers.Find(id);
            if (customerModel == null)
            {
                return HttpNotFound();
            }
            return View(customerModel);
        }

        // POST: CustomerModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustomerModel customerModel = db.Customers.Find(id);
            bool deleteAllowed = true;

           foreach (var item in db.CarRentals)
            {
                if (item.CustomerId == id)
                    deleteAllowed = false;
            }

            if (!deleteAllowed)
            {
                ModelState.AddModelError("errorDeleteCustomer", "You can't delete customer because he has rentals");;
                return View(customerModel);
            }
            else
            {
                db.Customers.Remove(customerModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RentCars/Views/CustomerModels/Create.cshtml
@model RentCars.Models.CustomerModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerSurname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerSurname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerSurname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Steet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Steet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Steet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coutry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coutry, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Coutry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RentCars/Views/CustomerModels/Delete.cshtml
@model RentCars.Models.CustomerModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerSurname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerSurname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Steet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Steet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coutry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coutry)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.ValidationMessage("errorDeleteCustomer")

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RentCars/Views/CustomerModels/Details.cshtml
@model RentCars.Models.CustomerModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerSurname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerSurname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Steet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Steet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coutry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coutry)
        </dd>

    </dl>
</div>
<div style="border:1px solid rgb(128, 128, 128);padding:15px;margin-top:15px">
    <h4>Car rentals history</h4>

    <div class="table-responsive">
        <table class="table table-bordered table-condensed table-striped table-hover sortable">
            @if (Model.CarRentals.Count() == 0)
            {
                <tr>
                    <td colspan="10">No Record's found.</td>
                </tr>
            }
            else
            {
                <thead>
                    <tr class="danger">
                        <th data-defaultsign="_19">Rate</th>
                        <th data-defaultsign="AZ">Car brand</th>
                        <th data-defaultsign="AZ">Car model</th>
                        <th data-defaultsign="_19">Production year</th>
                        <th data-defaultsign="AZ">Colour</th>
                    </tr>
                </thead>
                foreach (var item in Model.CarRentals)
                {
                <tr>

                    <td>@item.CarRentalRate</td>
                    <td>@item.Cars.Brand</td>
                    <td>@item.Cars.Model</td>
                    <td>@item.Cars.ProductionYear</td>
                    <td>@item.Cars.Colour</td>
                </tr>
                }
            }
        </table>
    </div>

</div>
<br />
<br />
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RentCars/Views/CustomerModels/Edit.cshtml
@model RentCars.Models.CustomerModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerId)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerSurname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerSurname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerSurname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Steet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Steet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Steet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coutry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coutry, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Coutry, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RentCars/Views/CustomerModels/Index.cshtml
@model IEnumerable<RentCars.Models.CustomerModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index of customers</h2>

<p>
    @Html.ActionLink("Create New Customer", "Create")
</p>

<div class="table-responsive">
    <table class="table table-bordered table-condensed table-striped table-hover sortable">
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="10">No Record's found.</td>
            </tr>
        }
        else
        {
            <thead>
                <tr class="danger">
                    <th data-defaultsign="AZ">Name</th>
                    <th data-defaultsign="AZ">Surname</th>
                    <th data-defaultsign="AZ">Street</th>
                    <th data-defaultsign="AZ">City</th>
                    <th data-defaultsign="AZ">PostCode</th>
                    <th data-defaultsign="AZ">Country</th>
                    <th data-defaultsort="disabled"></th>
                </tr>
            </thead>
            foreach (var item in Model)
            {
            <tr>
                <td>@item.CustomerName</td>
                <td>@item.CustomerSurname</td>
                <td>@item.Steet</td>
                <td>@item.City</td>
                <td>@item.PostCode</td>
                <td>@item.Coutry</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.CustomerId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.CustomerId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.CustomerId }) |                    
                    @Html.ActionLink("AddRental", "Create", "CarRentalModels", new { id = item.CustomerId }, null)
                </td>
            </tr>
            }
        }
    </table>
</div>